modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/Virtuoel/NoFog/issues"
[[mods]]
modId="no_fog"
version="${file.jarVersion}"
displayName="No Fog"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nofog/"
logoFile="assets/no_fog/icon.png"
authors="Virtuoel"
description='''
Removes different types of fog.
'''
[[mixins]]
config="no_fog.mixins.json"
